version: '3'
volumes:
  deb_repository:
services:
  scalable-debian:
    build:
      args:
      - RELOCALKEY=5F79F05B6A0D28E5
      - LOCALURL=10.17.102.198
      - LOCAL_URL=172.17.0.1:49161
      context: .
      dockerfile: Dockerfile_deb
    volumes:
      - deb_repository:/home/package
    image: scalable-deb:latest
