From registry.msb.scalable.atm.virtualfortknox.de/buildbot_scalable/buildbot-deb:0.0.1
ARG LOCAL_URL
RUN sh -c 'echo "deb http://$LOCAL_URL/ xenial main" >> /etc/apt/sources.list'
COPY ./build /tmp/
RUN apt-get update
