FROM ubuntu:18.04
MAINTAINER Ruichao WU
# If using a private distro, need to setup keys for github
RUN mkdir -p /root/.ssh
#ADD ./docker/ssh_master/id_rsa_worker.pub /root/.ssh/id_rsa_worker.pub
#RUN chmod 600 /root/.ssh/id_rsa_worker.pub
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa 
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install -q -y openssh-server \
    python3-dev python3 python3-venv \
    reprepro \
    debootstrap \
    devscripts \
    git \
    git-buildpackage \
    debhelper \
    debmirror
# enter virtualenv
ARG SSH_KEY=123
RUN echo "${SSH_KEY}" > /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts 
#RUN echo "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
RUN apt-get update
RUN /usr/bin/python3 -m venv /root/buildbot-env
RUN echo "export PATH=/root/buildbot-ros/scripts:${PATH}" >> /root/buildbot-env/bin/activate
# install pip dependencies
RUN /root/buildbot-env/bin/pip3 install --upgrade pip 
RUN /root/buildbot-env/bin/pip3 install rosdistro \
    treq 'buildbot[bundle]' docker-compose
#RUN git clone -b master git@github.com:mikeferguson/buildbot-ros.git /root/buildbot-ros
RUN apt-get install -y libpq-dev python-dev
RUN /root/buildbot-env/bin/pip install psycopg2-binary
ADD ./buildbot-ros /root/buildbot-ros
ADD ./rosdistro /root/rosdistro
WORKDIR /root
ADD ./docker/start_master.sh /root/start_master.sh


