services:
  scalable:
    build:
      args:
        LOCAL_RESPOSITORY: 172.17.0.1:49161
        SINGING_KEY: 8617EB404586F58E
      context: .
      dockerfile: Dockerfile_unique
    image: scalable-base:latest
    volumes:
    - deb_repository:/home/package
version: '3'
volumes:
  deb_repository: null
