From ros:kinetic-ros-core-xenial
RUN apt-get update && apt-get install -y \
   	ros-kinetic-ros-base \
	git \
	ros-kinetic-rosdoc-lite \
	apt-utils \
	doxygen \
	python-epydoc \
	python-sphinx \
	graphviz
ADD ./scripts/docbuild.py /root/docbuild.py
#ADD ./docker_components/rosdep_private.yaml /home/rosdep/private.yaml
#RUN sh -c 'echo "yaml file:///home/rosdep/private.yaml" >> /etc/ros/rosdep/sources.list.d/20-default.list'
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 28143562B0A851DD
RUN apt-get -y update
RUN apt-get -y upgrade