From registry.msb.scalable.atm.virtualfortknox.de/buildbot_scalable/buildbot-sys:base
ARG LOCAL_RESPOSITORY
RUN sh -c 'echo "deb http://$LOCAL_RESPOSITORY/ xenial main" >> /etc/apt/sources.list'
# local repository gpg key
ARG SINGING_KEY
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $SINGING_KEY
COPY ./scalable_ws /tmp/scalable_ws
RUN apt-get update

