# base
From ros:kinetic-ros-core-xenial
RUN apt-get update && apt-get install -y \
   	ros-kinetic-ros-base \
	git \
	dpkg-dev \
	debhelper \
	fakeroot \
	python-pip \
	software-properties-common\
	reprepro \
	apt-utils
RUN pip install --upgrade pip
RUN pip install -U bloom
ADD ./scripts/update_private_rosdep.py /home/rosdep/update_private_rosdep.py
RUN apt-get -y update
RUN apt-get -y upgrade
ADD ./shell/builddebian.sh /usr/local/sbin/builddeb.sh
RUN rosdep db
# From registry.msb.scalable.atm.virtualfortknox.de/buildbot_scalable/buildbot-deb:0.0.2
# local repository
ARG SINGING_KEY
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $SINGING_KEY
#ARG LOCAL_URL
#RUN sh -c 'echo "deb http://$LOCAL_URL/ xenial main" >> /etc/apt/sources.list'
COPY ./build /tmp/
RUN apt-get update
