version: '3'
volumes:
  deb_repository:
services:
  scalable-debian:
    build:
      args:
        SINGING_KEY: 
        LOCAL_RESPOSITORY: 172.17.0.1:49161
      context: .
      dockerfile: Dockerfile_deb
    volumes:
      - deb_repository:/home/package
    image: scalable-deb:latest
